### ISSUE TITLE
test.sh: 7 tests, failed, missing `pytest`

### ISSUE THREAD

**Issue by AronVanAmmers** [OutlierVentures/ANVIL#5]
Running `./test.sh` after `./install.sh` on Ubuntu 18.04.1. Some tests fail because of missing `pytest`.

I have `python3-pytest`. 

```
$ ./test.sh 
Testing Fetch install...
GLOB sdist-make: /home/aron/develop/ANVIL/scripts/oefpy/setup.py
py37 create: /home/aron/develop/ANVIL/scripts/oefpy/.tox/py37
py37 installdeps: pytest, pytest-cov, hypothesis, hypothesis-pytest
py37 inst: /home/aron/develop/ANVIL/scripts/oefpy/.tox/dist/oef-0.2.0.zip
py37 installed: atomicwrites==1.3.0,attrs==19.1.0,coverage==4.5.3,hypothesis==4.14.0,hypothesis-pytest==0.19.0,more-itertools==6.0.0,oef==0.2.0,pkg-resources==0.0.0,pluggy==0.9.0,protobuf==3.7.0,py==1.8.0,pytest==4.3.1,pytest-cov==2.6.1,six==1.12.0
py37 runtests: PYTHONHASHSEED='3330008068'
py37 runtests: commands[0] | python setup.py install
running install
running bdist_egg
running egg_info
writing oef.egg-info/PKG-INFO
writing dependency_links to oef.egg-info/dependency_links.txt
writing requirements to oef.egg-info/requires.txt
writing top-level names to oef.egg-info/top_level.txt
reading manifest file 'oef.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'oef.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running protoc
Running ['/usr/bin/protoc', '--proto_path=oef-core-protocol', '--python_out=oef', 'oef-core-protocol/query.proto', 'oef-core-protocol/fipa.proto', 'oef-core-protocol/agent.proto']
copying oef/agent_pb2.py -> build/lib/oef
copying oef/fipa_pb2.py -> build/lib/oef
copying oef/query_pb2.py -> build/lib/oef
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/oef
copying build/lib/oef/__init__.py -> build/bdist.linux-x86_64/egg/oef
copying build/lib/oef/logger.py -> build/bdist.linux-x86_64/egg/oef
copying build/lib/oef/core.py -> build/bdist.linux-x86_64/egg/oef
copying build/lib/oef/dialogue.py -> build/bdist.linux-x86_64/egg/oef
copying build/lib/oef/agent_pb2.py -> build/bdist.linux-x86_64/egg/oef
copying build/lib/oef/schema.py -> build/bdist.linux-x86_64/egg/oef
copying build/lib/oef/query.py -> build/bdist.linux-x86_64/egg/oef
copying build/lib/oef/proxy.py -> build/bdist.linux-x86_64/egg/oef
copying build/lib/oef/agents.py -> build/bdist.linux-x86_64/egg/oef
copying build/lib/oef/fipa_pb2.py -> build/bdist.linux-x86_64/egg/oef
copying build/lib/oef/__version__.py -> build/bdist.linux-x86_64/egg/oef
copying build/lib/oef/query_pb2.py -> build/bdist.linux-x86_64/egg/oef
copying build/lib/oef/messages.py -> build/bdist.linux-x86_64/egg/oef
copying build/lib/oef/helpers.py -> build/bdist.linux-x86_64/egg/oef
byte-compiling build/bdist.linux-x86_64/egg/oef/__init__.py to __init__.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/oef/logger.py to logger.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/oef/core.py to core.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/oef/dialogue.py to dialogue.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/oef/agent_pb2.py to agent_pb2.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/oef/schema.py to schema.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/oef/query.py to query.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/oef/proxy.py to proxy.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/oef/agents.py to agents.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/oef/fipa_pb2.py to fipa_pb2.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/oef/__version__.py to __version__.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/oef/query_pb2.py to query_pb2.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/oef/messages.py to messages.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/oef/helpers.py to helpers.cpython-37.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying oef.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying oef.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying oef.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying oef.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying oef.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/oef-0.2.0-py3.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing oef-0.2.0-py3.7.egg
Copying oef-0.2.0-py3.7.egg to /home/aron/develop/ANVIL/scripts/oefpy/.tox/py37/lib/python3.7/site-packages
Adding oef 0.2.0 to easy-install.pth file

Installed /home/aron/develop/ANVIL/scripts/oefpy/.tox/py37/lib/python3.7/site-packages/oef-0.2.0-py3.7.egg
Processing dependencies for oef==0.2.0
Searching for protobuf==3.7.0
Best match: protobuf 3.7.0
Adding protobuf 3.7.0 to easy-install.pth file

Using /home/aron/develop/ANVIL/scripts/oefpy/.tox/py37/lib/python3.7/site-packages
Searching for setuptools==40.8.0
Best match: setuptools 40.8.0
Adding setuptools 40.8.0 to easy-install.pth file
Installing easy_install script to /home/aron/develop/ANVIL/scripts/oefpy/.tox/py37/bin
Installing easy_install-3.6 script to /home/aron/develop/ANVIL/scripts/oefpy/.tox/py37/bin

Using /home/aron/develop/ANVIL/scripts/oefpy/.tox/py37/lib/python3.7/site-packages
Searching for six==1.12.0
Best match: six 1.12.0
Adding six 1.12.0 to easy-install.pth file

Using /home/aron/develop/ANVIL/scripts/oefpy/.tox/py37/lib/python3.7/site-packages
Finished processing dependencies for oef==0.2.0
py37 runtests: commands[1] | pytest --doctest-modules oef test --cov=oef --cov-report=html --cov-report=term
============================================================================================= test session starts ==============================================================================================
platform linux -- Python 3.7.2, pytest-4.3.1, py-1.8.0, pluggy-0.9.0
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/home/aron/develop/ANVIL/scripts/oefpy/.hypothesis/examples')
rootdir: /home/aron/develop/ANVIL/scripts/oefpy, inifile:
plugins: cov-2.6.1, hypothesis-4.14.0
collected 135 items                                                                                                                                                                                            

oef/logger.py .                                                                                                                                                                                          [  0%]
oef/query.py ...............                                                                                                                                                                             [ 11%]
oef/schema.py ...                                                                                                                                                                                        [ 14%]
test/test_agents.py ........                                                                                                                                                                             [ 20%]
test/test_logger.py ........................                                                                                                                                                             [ 37%]
test/test_proxy.py ..............................                                                                                                                                                        [ 60%]
test/test_query.py ........................                                                                                                                                                              [ 77%]
test/test_schema.py .................                                                                                                                                                                    [ 90%]
test/test_dialogue/test_group_dialogue.py .                                                                                                                                                              [ 91%]
test/test_dialogue/test_single_dialogue.py .....FFFFFFF                                                                                                                                                  [100%]

=================================================================================================== FAILURES ===================================================================================================
_____________________________________________________________________________________________ TestCFP.test_on_cfp ______________________________________________________________________________________________

self = <test.test_dialogue.test_single_dialogue.TestCFP object at 0x7f54105e8b00>

    def test_on_cfp(self):
        """Test that a dialogue agent can receive and handle a CFP correctly."""
    
        with NetworkOEFNode():
            dialogue_agent_0 = AgentSingleDialogueTest(OEFNetworkProxy("dialogue_agent_0", "127.0.0.1"))
>           dialogue_agent_0.connect()

test/test_dialogue/test_single_dialogue.py:103: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
oef/agents.py:122: in connect
    return self._loop.run_until_complete(self.async_connect())
/usr/lib/python3.7/asyncio/base_events.py:584: in run_until_complete
    return future.result()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <test.test_dialogue.dialogue_agents.AgentSingleDialogueTest object at 0x7f54105e8550>

    async def async_connect(self) -> bool:
        """
        The asynchronous counterpart of :func:`~oef.agents.Agent.connect`.
    
        :return: True if the connection has been established successfully, False otherwise.
        """
        logger.debug("{}: Connecting...".format(self.public_key))
        status = await self._oef_proxy.connect()
        if status:
            logger.debug("{}: Connection established.".format(self.public_key))
        else:
>           raise OEFConnectionError("Public key already in use.")
E           oef.proxy.OEFConnectionError: Public key already in use.

oef/agents.py:135: OEFConnectionError
_________________________________________________________________________ TestPropose.test_on_propose_as_first_message_gives_an_error __________________________________________________________________________

self = <test.test_dialogue.test_single_dialogue.TestPropose object at 0x7f54109d5470>

    def test_on_propose_as_first_message_gives_an_error(self):
        """Test that if the dialogue agent sends a propose as first message we get an Error."""
        with pytest.raises(KeyError, match="Dialogue key .* not found"):
            with NetworkOEFNode():
                dialogue_agent_0 = AgentSingleDialogueTest(OEFNetworkProxy("dialogue_agent_0", "127.0.0.1"))
>               dialogue_agent_0.connect()

test/test_dialogue/test_single_dialogue.py:124: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
oef/agents.py:122: in connect
    return self._loop.run_until_complete(self.async_connect())
/usr/lib/python3.7/asyncio/base_events.py:584: in run_until_complete
    return future.result()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <test.test_dialogue.dialogue_agents.AgentSingleDialogueTest object at 0x7f5410556a90>

    async def async_connect(self) -> bool:
        """
        The asynchronous counterpart of :func:`~oef.agents.Agent.connect`.
    
        :return: True if the connection has been established successfully, False otherwise.
        """
        logger.debug("{}: Connecting...".format(self.public_key))
        status = await self._oef_proxy.connect()
        if status:
            logger.debug("{}: Connection established.".format(self.public_key))
        else:
>           raise OEFConnectionError("Public key already in use.")
E           oef.proxy.OEFConnectionError: Public key already in use.

oef/agents.py:135: OEFConnectionError
_________________________________________________________________________________________ TestPropose.test_on_propose __________________________________________________________________________________________

self = <test.test_dialogue.test_single_dialogue.TestPropose object at 0x7f54104a9048>

    def test_on_propose(self):
        """Test that a dialogue agent can receive and handle a Propose correctly."""
        with NetworkOEFNode():
            dialogue_agent_0 = AgentSingleDialogueTest(OEFNetworkProxy("dialogue_agent_0", "127.0.0.1"))
>           dialogue_agent_0.connect()

test/test_dialogue/test_single_dialogue.py:135: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
oef/agents.py:122: in connect
    return self._loop.run_until_complete(self.async_connect())
/usr/lib/python3.7/asyncio/base_events.py:584: in run_until_complete
    return future.result()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <test.test_dialogue.dialogue_agents.AgentSingleDialogueTest object at 0x7f54104a93c8>

    async def async_connect(self) -> bool:
        """
        The asynchronous counterpart of :func:`~oef.agents.Agent.connect`.
    
        :return: True if the connection has been established successfully, False otherwise.
        """
        logger.debug("{}: Connecting...".format(self.public_key))
        status = await self._oef_proxy.connect()
        if status:
            logger.debug("{}: Connection established.".format(self.public_key))
        else:
>           raise OEFConnectionError("Public key already in use.")
E           oef.proxy.OEFConnectionError: Public key already in use.

oef/agents.py:135: OEFConnectionError
__________________________________________________________________________ TestAccept.test_on_accept_as_first_message_gives_an_error ___________________________________________________________________________

self = <test.test_dialogue.test_single_dialogue.TestAccept object at 0x7f54106870b8>

    def test_on_accept_as_first_message_gives_an_error(self):
        """Test that if the dialogue agent sends an accept as first message we get an Error."""
        with pytest.raises(KeyError, match="Dialogue key .* not found"):
            with NetworkOEFNode():
                dialogue_agent_0 = AgentSingleDialogueTest(OEFNetworkProxy("dialogue_agent_0", "127.0.0.1"))
>               dialogue_agent_0.connect()

test/test_dialogue/test_single_dialogue.py:158: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
oef/agents.py:122: in connect
    return self._loop.run_until_complete(self.async_connect())
/usr/lib/python3.7/asyncio/base_events.py:584: in run_until_complete
    return future.result()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <test.test_dialogue.dialogue_agents.AgentSingleDialogueTest object at 0x7f54106c16a0>

    async def async_connect(self) -> bool:
        """
        The asynchronous counterpart of :func:`~oef.agents.Agent.connect`.
    
        :return: True if the connection has been established successfully, False otherwise.
        """
        logger.debug("{}: Connecting...".format(self.public_key))
        status = await self._oef_proxy.connect()
        if status:
            logger.debug("{}: Connection established.".format(self.public_key))
        else:
>           raise OEFConnectionError("Public key already in use.")
E           oef.proxy.OEFConnectionError: Public key already in use.

oef/agents.py:135: OEFConnectionError
__________________________________________________________________________________________ TestAccept.test_on_propose __________________________________________________________________________________________

self = <test.test_dialogue.test_single_dialogue.TestAccept object at 0x7f54105407b8>

    def test_on_propose(self):
        """Test that a dialogue agent can receive and handle a Accept correctly."""
        with NetworkOEFNode():
            dialogue_agent_0 = AgentSingleDialogueTest(OEFNetworkProxy("dialogue_agent_0", "127.0.0.1"))
>           dialogue_agent_0.connect()

test/test_dialogue/test_single_dialogue.py:169: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
oef/agents.py:122: in connect
    return self._loop.run_until_complete(self.async_connect())
/usr/lib/python3.7/asyncio/base_events.py:584: in run_until_complete
    return future.result()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <test.test_dialogue.dialogue_agents.AgentSingleDialogueTest object at 0x7f5410540c18>

    async def async_connect(self) -> bool:
        """
        The asynchronous counterpart of :func:`~oef.agents.Agent.connect`.
    
        :return: True if the connection has been established successfully, False otherwise.
        """
        logger.debug("{}: Connecting...".format(self.public_key))
        status = await self._oef_proxy.connect()
        if status:
            logger.debug("{}: Connection established.".format(self.public_key))
        else:
>           raise OEFConnectionError("Public key already in use.")
E           oef.proxy.OEFConnectionError: Public key already in use.

oef/agents.py:135: OEFConnectionError
_________________________________________________________________________ TestDecline.test_on_decline_as_first_message_gives_an_error __________________________________________________________________________

self = <test.test_dialogue.test_single_dialogue.TestDecline object at 0x7f5410767128>

    def test_on_decline_as_first_message_gives_an_error(self):
        """Test that if the dialogue agent sends an accept as first message we get an Error."""
        with pytest.raises(KeyError, match="Dialogue key .* not found"):
            with NetworkOEFNode():
                dialogue_agent_0 = AgentSingleDialogueTest(OEFNetworkProxy("dialogue_agent_0", "127.0.0.1"))
>               dialogue_agent_0.connect()

test/test_dialogue/test_single_dialogue.py:194: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
oef/agents.py:122: in connect
    return self._loop.run_until_complete(self.async_connect())
/usr/lib/python3.7/asyncio/base_events.py:584: in run_until_complete
    return future.result()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <test.test_dialogue.dialogue_agents.AgentSingleDialogueTest object at 0x7f5410776f98>

    async def async_connect(self) -> bool:
        """
        The asynchronous counterpart of :func:`~oef.agents.Agent.connect`.
    
        :return: True if the connection has been established successfully, False otherwise.
        """
        logger.debug("{}: Connecting...".format(self.public_key))
        status = await self._oef_proxy.connect()
        if status:
            logger.debug("{}: Connection established.".format(self.public_key))
        else:
>           raise OEFConnectionError("Public key already in use.")
E           oef.proxy.OEFConnectionError: Public key already in use.

oef/agents.py:135: OEFConnectionError
_________________________________________________________________________________________ TestDecline.test_on_decline __________________________________________________________________________________________

self = <test.test_dialogue.test_single_dialogue.TestDecline object at 0x7f54104a9828>

    def test_on_decline(self):
        """Test that a dialogue agent can receive and handle a Accept correctly."""
        with NetworkOEFNode():
            dialogue_agent_0 = AgentSingleDialogueTest(OEFNetworkProxy("dialogue_agent_0", "127.0.0.1"))
>           dialogue_agent_0.connect()

test/test_dialogue/test_single_dialogue.py:205: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
oef/agents.py:122: in connect
    return self._loop.run_until_complete(self.async_connect())
/usr/lib/python3.7/asyncio/base_events.py:584: in run_until_complete
    return future.result()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <test.test_dialogue.dialogue_agents.AgentSingleDialogueTest object at 0x7f54104a9a90>

    async def async_connect(self) -> bool:
        """
        The asynchronous counterpart of :func:`~oef.agents.Agent.connect`.
    
        :return: True if the connection has been established successfully, False otherwise.
        """
        logger.debug("{}: Connecting...".format(self.public_key))
        status = await self._oef_proxy.connect()
        if status:
            logger.debug("{}: Connection established.".format(self.public_key))
        else:
>           raise OEFConnectionError("Public key already in use.")
E           oef.proxy.OEFConnectionError: Public key already in use.

oef/agents.py:135: OEFConnectionError
=============================================================================================== warnings summary ===============================================================================================
.tox/py37/lib/python3.7/site-packages/google/protobuf/descriptor.py:47
  /home/aron/develop/ANVIL/scripts/oefpy/.tox/py37/lib/python3.7/site-packages/google/protobuf/descriptor.py:47: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    from google.protobuf.pyext import _message

test/test_proxy.py::TestSimpleMessage::test_on_message[local]
test/test_proxy.py::TestSimpleMessage::test_on_message[networked]
test/test_proxy.py::TestCFP::test_on_cfp[local]
test/test_proxy.py::TestCFP::test_on_cfp[networked]
test/test_proxy.py::TestPropose::test_on_propose[local]
test/test_proxy.py::TestPropose::test_on_propose[networked]
test/test_proxy.py::TestAccept::test_on_accept[local]
test/test_proxy.py::TestAccept::test_on_accept[networked]
test/test_proxy.py::TestDecline::test_on_decline[local]
test/test_proxy.py::TestDecline::test_on_decline[networked]
test/test_proxy.py::TestSearchServices::test_on_search_result_services[local]
test/test_proxy.py::TestSearchServices::test_on_search_result_services[networked]
test/test_proxy.py::TestSearchAgents::test_on_search_result_agents[local]
test/test_proxy.py::TestSearchAgents::test_on_search_result_agents[networked]
test/test_proxy.py::TestUnregisterAgent::test_unregister_agent[local]
test/test_proxy.py::TestUnregisterAgent::test_unregister_agent[networked]
test/test_proxy.py::TestUnregisterService::test_unregister_service[local]
test/test_proxy.py::TestUnregisterService::test_unregister_service[networked]
test/test_proxy.py::TestOEFError::test_oef_error_when_failing_in_unregistering_service
test/test_proxy.py::TestDialogueError::test_dialogue_error_when_destination_is_not_connected
  /home/aron/develop/ANVIL/scripts/oefpy/test/common.py:147: PendingDeprecationWarning: Task.all_tasks() is deprecated, use asyncio.all_tasks() instead
    tasks = asyncio.Task.all_tasks(asyncio.get_event_loop())

-- Docs: https://docs.pytest.org/en/latest/warnings.html

----------- coverage: platform linux, python 3.7.2-final-0 -----------
Name                 Stmts   Miss  Cover
----------------------------------------
oef/__init__.py          4      0   100%
oef/__version__.py       8      0   100%
oef/agent_pb2.py       139      0   100%
oef/agents.py          106      0   100%
oef/core.py            112      2    98%
oef/dialogue.py        115     14    88%
oef/fipa_pb2.py         62      0   100%
oef/helpers.py          12      0   100%
oef/logger.py           13      0   100%
oef/messages.py        178      0   100%
oef/proxy.py           246      0   100%
oef/query.py           407      0   100%
oef/query_pb2.py       183      0   100%
oef/schema.py          152      0   100%
----------------------------------------
TOTAL                 1737     16    99%
Coverage HTML written to dir htmlcov

============================================================================== 7 failed, 128 passed, 21 warnings in 16.62 seconds ==============================================================================
ERROR: InvocationError: '/home/aron/develop/ANVIL/scripts/oefpy/.tox/py37/bin/pytest --doctest-modules oef test --cov=oef --cov-report=html --cov-report=term'
___________________________________________________________________________________________________ summary ____________________________________________________________________________________________________
ERROR:   py37: commands failed
Testing Sovrin install...
./test.sh: line 19: pytest: command not found
Tests complete, see results above.
```

**Comment by AronVanAmmers** [comment]
Installing `python-pytest` doesn't help, gives the below as final output:

```
============================================================================== 7 failed, 128 passed, 21 warnings in 15.81 seconds ==============================================================================
ERROR: InvocationError: '/home/aron/develop/ANVIL/scripts/oefpy/.tox/py37/bin/pytest --doctest-modules oef test --cov=oef --cov-report=html --cov-report=term'
___________________________________________________________________________________________________ summary ____________________________________________________________________________________________________
ERROR:   py37: commands failed
Testing Sovrin install...
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/_pytest/config.py", line 365, in _importconftest
    mod = conftestpath.pyimport()
  File "/usr/lib/python2.7/dist-packages/py/_path/local.py", line 668, in pyimport
    __import__(modname)
  File "/home/aron/develop/ANVIL/scripts/indy/wrappers/python/tests/conftest.py", line 120
    def path_home() -> Path:
                    ^
SyntaxError: invalid syntax
ERROR: could not load /home/aron/develop/ANVIL/scripts/indy/wrappers/python/tests/conftest.py

Tests complete, see results above.
```

**Comment by theoturner** [comment]
Next public release of Fetch. Please see this issue on the [OEF Python SDK repo](https://github.com/fetchai/oef-sdk-python/issues/2) for progress.
