### ISSUE TITLE
Internal server error after Reset on Prover

### ISSUE THREAD

**Issue by AronVanAmmers** [OutlierVentures/ANVIL#7]
Console log:

```
[2019-03-26 12:17:35,407] 127.0.0.1:40368 GET / 1.1 200 528 9528
Setting up pool...
_indy_loop_callback: Function returned error (<ErrorCode.PoolLedgerConfigAlreadyExistsError: 306>, 'Error: Pool ledger config already exists\n  Caused by: Pool ledger config file with name "ANVIL" already exists\n')
_indy_loop_callback: Function returned error (<ErrorCode.PoolLedgerInvalidPoolHandle: 301>, 'Error: Invalid pool handle\n  Caused by: Pool with the same name is already opened\n')
[2019-03-26 12:18:20,860] ERROR in app: Exception on request POST /setup
Traceback (most recent call last):
  File "/home/aron/.local/lib/python3.6/site-packages/quart/app.py", line 1449, in handle_request
    return await self.full_dispatch_request(request_context)
  File "/home/aron/.local/lib/python3.6/site-packages/quart/app.py", line 1471, in full_dispatch_request
    result = await self.handle_user_exception(error)
  File "/home/aron/.local/lib/python3.6/site-packages/quart/app.py", line 892, in handle_user_exception
    raise error
  File "/home/aron/.local/lib/python3.6/site-packages/quart/app.py", line 1469, in full_dispatch_request
    result = await self.dispatch_request(request_context)
  File "/home/aron/.local/lib/python3.6/site-packages/quart/app.py", line 1517, in dispatch_request
    return await handler(**request_.view_args)
  File "prover.py", line 47, in setup
    prover, pool_handle = await common_setup(prover, pool_handle, 'prover')
  File "/home/aron/develop/ANVIL/anvil/common.py", line 17, in common_setup
    _, pool_handle = await setup_pool('local')
  File "/home/aron/develop/ANVIL/anvil/sovrin/setup.py", line 41, in setup_pool
    pool_['handle'] = await pool.open_pool_ledger(pool_['name'], None)
  File "/home/aron/.local/lib/python3.6/site-packages/indy/pool.py", line 82, in open_pool_ledger
    open_pool_ledger.cb)
indy.error.IndyError: (<ErrorCode.PoolLedgerInvalidPoolHandle: 301>, 'Error: Invalid pool handle\n  Caused by: Pool with the same name is already opened\n')
```

**Comment by theoturner** [comment]
Fixed in #49841b5
