### ISSUE TITLE
Key error when offering credential to Prover

### ISSUE THREAD

**Issue by AronVanAmmers** [OutlierVentures/ANVIL#8]
In Issuer:

1. Create credential schema from example degree_certificate
2. Offer schema degree_certificate to Prover on 127.0.0.1:5002

Result: Internal Server Error, below log on Issuer console.

```
[2019-03-26 12:22:20,937] 127.0.0.1:47392 GET / 1.1 200 1724 3787
Issuer offering credential to Prover...
[2019-03-26 12:22:41,222] ERROR in app: Exception on request POST /offer_credential
Traceback (most recent call last):
  File "/home/aron/.local/lib/python3.6/site-packages/quart/app.py", line 1449, in handle_request
    return await self.full_dispatch_request(request_context)
  File "/home/aron/.local/lib/python3.6/site-packages/quart/app.py", line 1471, in full_dispatch_request
    result = await self.handle_user_exception(error)
  File "/home/aron/.local/lib/python3.6/site-packages/quart/app.py", line 892, in handle_user_exception
    raise error
  File "/home/aron/.local/lib/python3.6/site-packages/quart/app.py", line 1469, in full_dispatch_request
    result = await self.dispatch_request(request_context)
  File "/home/aron/.local/lib/python3.6/site-packages/quart/app.py", line 1517, in dispatch_request
    return await handler(**request_.view_args)
  File "issuer.py", line 119, in offer_credential_to_ip
    issuer, cred_offer = await offer_credential(issuer, schema_name)
  File "/home/aron/develop/ANVIL/anvil/sovrin/credentials.py", line 30, in offer_credential
    await crypto.auth_crypt(issuer['wallet'], issuer['prover_key'], issuer['prover_key_for_issuer'],
KeyError: 'prover_key'
[2019-03-26 12:22:41,234] 127.0.0.1:47426 POST /offer_credential 1.1 500 126 26218
```

**Comment by theoturner** [comment]
The issuer data structure is missing the prover key but has its own wallet set up, so this means route `/offer_credential` has been accessed before establishing a channel. Unable to reproduce with the above steps – given the date of filing, please update to latest - this should no longer be an issue.
